CREATE TABLE IF NOT EXISTS tracks (
  id INTEGER PRIMARY KEY,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  rating REAL NOT NULL DEFAULT 1500
);
CREATE INDEX IF NOT EXISTS tracks_by_rating ON tracks (rating DESC);

CREATE TABLE IF NOT EXISTS limits (
  ip TEXT PRIMARY KEY,
  hour INTEGER NOT NULL,
  count INTEGER NOT NULL
);
